name: test-migration
on:
  push:
    branches:
      - main
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  test-migration:
    name: "test-migration"
    runs-on: ubuntu-latest
    services:
      db:
        image: mariadb:10.10.2
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: lullaby_test
          MYSQL_USER: lullaby
          MYSQL_PASSWORD: lullaby
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK 7.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.100'
      - name: Install dependencies
        run: dotnet restore && dotnet tool restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test migrations
        run: dotnet ef database update --project Lullaby -- --environment Testing
