name: test-migration
on:
  push:
    branches:
      - main
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  test-migration:
    name: "test-migration"
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:16.4
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: lullaby
          POSTGRES_USER: lullaby
          POSTGRES_PASSWORD: lullaby
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      - name: Install dependencies
        run: dotnet restore && dotnet tool restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test migrations
        run: dotnet ef database update --project Lullaby -- --environment Testing
